apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: okteto.dev/python-hello-world:1.0.0
        name: hello-world
      env:
      - name: REDIS_HOST
          value:  ${REDIS_HOST}
      - name: REDIS_PASSWD
          value:  ${REDIS_PASSWD}
      - name: FLASK_USER
          value:  ${FLASK_USER}
      - name: FLASK_PASSWD
          value:  ${FLASK_PASSWD}
---

apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: ClusterIP
  ports:
  - name: "hello-world"
    port: 8080
  selector:
    app: hello-world

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    dev.okteto.com/generate-host: hello-world
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: hello-world
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
